"""grade overridden flag

Revision ID: 30c746b0750b
Revises: 7ac2ed67319f
Create Date: 2026-07-09 12:39:07.753048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c746b0750b'
down_revision: Union[str, Sequence[str], None] = '7ac2ed67319f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_sessions', sa.Column('grade_overridden', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_sessions', 'grade_overridden')
    # ### end Alembic commands ###
