"""collections quality feedback content events

Revision ID: 110c71b99113
Revises: 26ec53aaa89b
Create Date: 2026-07-09 11:24:04.169367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '110c71b99113'
down_revision: Union[str, Sequence[str], None] = '26ec53aaa89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_events_event_type'), 'content_events', ['event_type'], unique=False)
    op.create_table('lesson_collections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_sequential', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_collections_owner_id'), 'lesson_collections', ['owner_id'], unique=False)
    op.create_table('lesson_collection_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['lesson_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'lesson_id', name='uq_collection_lesson')
    )
    op.create_index(op.f('ix_lesson_collection_items_collection_id'), 'lesson_collection_items', ['collection_id'], unique=False)
    op.create_index(op.f('ix_lesson_collection_items_lesson_id'), 'lesson_collection_items', ['lesson_id'], unique=False)
    op.create_table('lesson_quality_feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_quality_feedback_lesson_id'), 'lesson_quality_feedback', ['lesson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_quality_feedback_lesson_id'), table_name='lesson_quality_feedback')
    op.drop_table('lesson_quality_feedback')
    op.drop_index(op.f('ix_lesson_collection_items_lesson_id'), table_name='lesson_collection_items')
    op.drop_index(op.f('ix_lesson_collection_items_collection_id'), table_name='lesson_collection_items')
    op.drop_table('lesson_collection_items')
    op.drop_index(op.f('ix_lesson_collections_owner_id'), table_name='lesson_collections')
    op.drop_table('lesson_collections')
    op.drop_index(op.f('ix_content_events_event_type'), table_name='content_events')
    op.drop_table('content_events')
    # ### end Alembic commands ###
