"""initial content schema

Revision ID: 26ec53aaa89b
Revises: 
Create Date: 2026-07-09 11:14:28.327894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26ec53aaa89b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('processing_status', sa.String(length=16), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_sha256'), 'files', ['sha256'], unique=True)
    op.create_table('lessons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('origin_lesson_id', sa.Uuid(), nullable=True),
    sa.Column('derivation_type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['origin_lesson_id'], ['lessons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_owner_id'), 'lessons', ['owner_id'], unique=False)
    op.create_index('uq_one_copy_per_owner', 'lessons', ['origin_lesson_id', 'owner_id'], unique=True, postgresql_where=sa.text("derivation_type = 'copy'"))
    op.create_table('teacher_quota',
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('storage_bytes', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_table('sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('origin_section_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origin_section_id'], ['sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_lesson_id'), 'sections', ['lesson_id'], unique=False)
    op.create_table('task_contents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_contents_content_hash'), 'task_contents', ['content_hash'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('origin_task_id', sa.Uuid(), nullable=True),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('current_content_id', sa.Uuid(), nullable=False),
    sa.Column('synced_from_content_id', sa.Uuid(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_content_id'], ['task_contents.id'], ),
    sa.ForeignKeyConstraint(['origin_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['synced_from_content_id'], ['task_contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_current_content_id'), 'tasks', ['current_content_id'], unique=False)
    op.create_index(op.f('ix_tasks_section_id'), 'tasks', ['section_id'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_section_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_current_content_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_task_contents_content_hash'), table_name='task_contents')
    op.drop_table('task_contents')
    op.drop_index(op.f('ix_sections_lesson_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_table('teacher_quota')
    op.drop_index('uq_one_copy_per_owner', table_name='lessons', postgresql_where=sa.text("derivation_type = 'copy'"))
    op.drop_index(op.f('ix_lessons_owner_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_files_sha256'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
